name: Build docker image and run unit tests

on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        load: true
        push: false
        tags: my_django_chat:latest

    - name: Copy and load .env.example file
      run: |
        cp .env.example .env

    - name: Run Docker container
      run: |
        docker-compose up -d

    - name: Run tests in docker container
      run: |
        chmod +x ./scripts/run_tests.sh
        ./scripts/run_tests.sh

    - name: Stop containers
      if: always()
      run: |
        docker compose down